scrape_configs:
- job_name: 'streamiz-application'
  scrape_interval: 5s
  static_configs:
  - targets:
    - consumer:1234
  metrics_path: /metrics
- job_name: 'spring-boot-application'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets:
    - 'localhost:8080'
